# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chatMessage.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63hatMessage.proto\x12\x13grpcServer.protobuf\"8\n\x0b\x43hatMessage\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0c\n\x04user\x18\x03 \x01(\t\"8\n\x0b\x43hatRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0c\n\x04user\x18\x03 \x01(\t\"%\n\x12\x43hatCreateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x18\n\nGetRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x32\xa5\x01\n\nChatServer\x12L\n\x06\x43reate\x12 .grpcServer.protobuf.ChatRequest\x1a .grpcServer.protobuf.ChatMessage\x12I\n\x04Read\x12\x1f.grpcServer.protobuf.GetRequest\x1a .grpcServer.protobuf.ChatMessageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chatMessage_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CHATMESSAGE']._serialized_start=42
  _globals['_CHATMESSAGE']._serialized_end=98
  _globals['_CHATREQUEST']._serialized_start=100
  _globals['_CHATREQUEST']._serialized_end=156
  _globals['_CHATCREATERESPONSE']._serialized_start=158
  _globals['_CHATCREATERESPONSE']._serialized_end=195
  _globals['_GETREQUEST']._serialized_start=197
  _globals['_GETREQUEST']._serialized_end=221
  _globals['_CHATSERVER']._serialized_start=224
  _globals['_CHATSERVER']._serialized_end=389
# @@protoc_insertion_point(module_scope)
